# http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html
#
development:
  adapter: postgresql
  encoding: unicode
  database: action_mailbox_development
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000
  username: postgres
  password: postgres